---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app
  labels:
    app: counter-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
      - name: counter-app
        image: prasannay/counter-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: test
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin123
