# Secret YAML file for MySQL database credentials
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  #not giving username and password as it is not secure to use it in public repo.
  password: test1234
